name: Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Bump version and push tag
        id: bump_version
        uses: mathieudutour/github-tag-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: .*

      - name: Cancel this build if no new commits
        if: ${{ steps.bump_version.outputs.new_tag == null }}
        uses: andymckay/cancel-action@0.2

      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          release_name: Release ${{ steps.bump_version.outputs.new_tag }}
          draft: false
          body: |
            Release built from commit [`${{ github.sha }}`](https://github.com/NEXTEP-CXS/nextep_dexv2/tree/${{ github.sha }})
            ${{ steps.bump_version.outputs.changelog }}